# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  image:
    repository: null
    tag: latest
    pullPolicy: Always

  # either StatefulSet, Deployment, or Job
  type: Deployment

  # IGNORED FOR JOBS.
  replicaCount: 1

  # port(s) of the container to expose
  # port can be a number or an array if you wish to open multiple ports
  # IGNORED FOR JOBS.
  port: 8000

  # Path for health check
  # IGNORED FOR JOBS.
  health: "/health/"

  # Either "Recreate" or "RollingUpdate". For rolling updates, please make sure your images
  # are tagged with a new version in each build.
  # IGNORED FOR STATEFULSETS AND JOBS.
  updateStrategy: Recreate

  # Define extra environment variables for your application
  extraEnv: |
    - name: PYTHONUNBUFFERED
      value: "1"

  # IGNORED FOR JOBS.
  readinessProbe: |
    httpGet:
      path: {{ .Values.app.health }}
      {{- if eq (typeOf .Values.app.port) "[]interface {}" }}
      port: {{ first .Values.app.port }}
      {{- else }}
      port: {{ .Values.app.port }}
      {{- end }}
    initialDelaySeconds: 3
    timeoutSeconds: 120
    periodSeconds: 120
    failureThreshold: 3
    successThreshold: 1

  # IGNORED FOR JOBS.
  livenessProbe: |
    httpGet:
      path: {{ .Values.app.health }}
      {{- if eq (typeOf .Values.app.port) "[]interface {}" }}
      port: {{ first .Values.app.port }}
      {{- else }}
      port: {{ .Values.app.port }}
      {{- end }}
    initialDelaySeconds: 6
    timeoutSeconds: 120
    periodSeconds: 120
    failureThreshold: 4
    successThreshold: 1

  # IGNORED FOR JOBS.
  startupProbe: null

  requests:
    cpu: null
    memory: null
    ephemeralStorage: null
    gpu: false
  limits:
    cpu: null
    memory: null
    ephemeralStorage: null

  pvc:
    enabled: false
    # Use this if you want to mount an already existing claim. Remember to set the name below if this is true.
    existingClaim: false
    # The name of the PVC to use. If not set, the name of the release will be used. Required if existingClaim is true.
    name: null
    accessMode: ReadWriteMany
    storage: 1Gi
    mountPath: "/tmp/app"

  # IGNORED FOR JOBS.
  ingress:
    enabled: true
    url: null
